databases:
  - name: otom
    databaseName: otom_db_6tp4
    user: tks930828
    region: Oregon

services:
  - type: web
    name: otom
    env: ruby
    region: Oregon
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    preDeployCommand: ./bin/rails db:migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: otom
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
    releaseCommand: DISABLE_DATABASE_ENVIRONMENT_CHECK=1 bundle exec rails db:migrate:reset